spring.application.name=ems
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ems}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:January@2020}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.bill-upload-dir=uploads\bills
